repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        language_version: python3.11

-    repo: https://github.com/psf/black-pre-commit-mirror
     rev: 24.3.0
     hooks:
        - id: black
          language_version: python3.11

-     repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          name: isort (python)
          language_version: python3.11
          args: ["--profile", "black", "--filter-files"]
