name: 'Deploying'

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define env vars
        run: |
          echo "${{ secrets.PROD_ENV_VARS }}" > .env

      - name: Build Docker image
        run: docker build -t axegaoshop:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o axegaoshop.tar axegaoshop:latest
          chmod 664 ${{ secrets.PROJECT_NAME }}.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.PROJECT_NAME }}.tar
          target: ${{ secrets.REMOTE_SERVER_PATH }}

      - name: Creating docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker load -i ${{ secrets.REMOTE_SERVER_PATH }}/${{ secrets.PROJECT_NAME }}.tar && rm -f ${{ secrets.REMOTE_SERVER_PATH }}/${{ secrets.PROJECT_NAME }}.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: docker-compose.yml
          target: ${{ secrets.REMOTE_SERVER_PATH }}

      - name: Starting containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml down
            docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml up -d
            docker system prune -a

      - name: Pulling uploading if needed
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -a
            source ${{ secrets.REMOTE_SERVER_PATH }}/.env
            set +a
            if [ "$PULL_UPLOADS" = "true" ]; then docker cp ${{ secrets.REMOTE_SERVER_PATH }}/${{ secrets.PROJECT_NAME }}/data/storage/uploads/. axegaoshop_api:/code/${{ secrets.PROJECT_NAME }}/data/storage/uploads/; echo "Файлы успешно перенесены в контейнер."; else echo "Переменная окружения PULL_UPLOADS не установлена в true. Пропускаем перенос файлов."; fi

      - name: Starting migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml exec -T web sh -c 'aerich upgrade'
